import AuthProvider from "@/components/AuthProvider";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  return (
    <html lang='en'>
      <body>
       <AuthProvider>
        {children}
       </AuthProvider>
      </body>
    </html>
  );
}
